### ISSUE TITLE
add support caseRaw

### ISSUE THREAD

**Issue by entense** [aglipanci/laravel-eloquent-case#2]
CaseRaw support required

To be able to do things like this

**case count(*)**

an example of how it would look in code

``` php
CaseBuilder::caseRaw('count(id)')
    ->whenRaw(0)->then(0)
    ->else(100)
    ->toRaw();
```

output

``` 
case count(id) when 0 then 0 else 100 end
```

**Comment by eduardlleshi** [comment]
@entense this has been added in `1.4.0`
