### ISSUE TITLE
Question - Are updates supported?

### ISSUE THREAD

**Issue by PerryRylance** [aglipanci/laravel-eloquent-case#7]

**Comment by aglipanci** [comment]
@PerryRylance what do you mean?

**Comment by PerryRylance** [comment]
As in `UPDATE table SET column CASE WHEN something = x THEN 1 ELSE 2 END`

**Comment by aglipanci** [comment]
I thought you were referring to the package maintenance 🤦‍♂️

Regarding your question, you can’t achieve that directly but you can build the CASE part of the query using the package and use as a raw query.

I hope that answers your question.
