### ISSUE TITLE
Chaining case with select

### ISSUE THREAD

**Issue by JonasFocke01** [aglipanci/laravel-eloquent-case#8]
Hello,

I have a query, that joins some things, needs to apply a case and also select stuff from the table.
Like this
```php
$table->join('another_table')
->case(function (CaseBuilder $case){
    $case->when('col1', '=', 'abc')->then(1)->else(0)
}, relevant)
->select('another_table.*', 'relevant')
->where('relevant', '=', '1')
->where('another_table.col2', '=', 'cba')
```
My problem is, that `case` and `select` seem to not see one another. How would i write that, so that all colums from `another_table` and also `relevant` appear in the result, so that i could access `relevant` in my where clause?

Thank You!!

**Comment by aglipanci** [comment]
@JonasFocke01 maybe it would be much easier to use selectRaw with $caseQuery->toSql();  in this case.
